version: '3.7'

services: 

  # db: mongo
  
  # broker: rabbitmq

  server1:
    container_name: full_env_node_server1
    build:
      context: ./server1
    ports:
      - $SERVER1_PORT:$SERVER1_PORT
      - $SERVER1_DEBUG_PORT:$SERVER1_DEBUG_PORT
    volumes:
      - ./server1:/var/www/html/server1
    environment:
      - PORT=$SERVER1_PORT
    # depends_on: 
    #   - db
    #   - broker

  server2:
    container_name: full_env_node_server2
    build:
      context: ./server2
    ports:
      - $SERVER2_PORT:$SERVER2_PORT
      - $SERVER2_DEBUG_PORT:$SERVER2_DEBUG_PORT
    volumes:
      - ./server2:/var/www/html/server2
    environment:
      - PORT=$SERVER2_PORT
    # depends_on: 
    #   - db
    #   - broker

  client:
    container_name: full_env_react_client
    build:
      context: ./client
      # args:
      #   - port=$CLIENT_PORT
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./client:/var/www/html/client
    depends_on: 
      - server1
      - server2
   