version: '3.7'

services: 

  # db: mongo
  
  # broker: rabbitmq

  server1:
    container_name: full_env_node_server1
    build:
      context: ./server1
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server1:/var/www/html/server1
    environment:
      - PORT=3000
    # depends_on: 
    #   - db

  # server2:
  #   container_name: full_env_node_server2
  #   build:
  #     context: ./server2
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./server2:/var/www/html/server2
  #   environment:
  #     - PORT=3001

  # client: react